(define (problem map-3)
    (:domain shakey)
    (:requirements :strips :typing)
    (:objects A B C D E F G H I J K L M N O P Q R - place
    )
    (:init
        (neighbour A B)
        (neighbour B A)
        (neighbour A C)
        (neighbour C A)
        (neighbour B C)
        (neighbour C B)
        (neighbour C R)
        (neighbour R C)
        (neighbour R Q)
        (neighbour Q R)
        (neighbour Q F)
        (neighbour F Q)
        (neighbour Q P)
        (neighbour P Q)
        (neighbour F E)
        (neighbour E F)
        (neighbour F D)
        (neighbour D F)
        (neighbour D E)
        (neighbour E D)
        (neighbour P I)
        (neighbour I P)
        (neighbour I H)
        (neighbour H I)
        (neighbour H G)
        (neighbour G H)
        (neighbour P O)
        (neighbour O P)
        (neighbour O N)
        (neighbour N O)
        (neighbour N M)
        (neighbour M N)
        (neighbour N L)
        (neighbour L N)
        (neighbour L M)
        (neighbour M L)
        (neighbour M K)
        (neighbour K M)
        (neighbour K L)
        (neighbour L K)
        (neighbour J K)
        (neighbour K J)


        (hasShakey D)

        (hasSwitchOff C)
        (hasSwitchOn F)
        (hasSwitchOn I)
        (hasSwitchOff N)

        (hasBox J)
        (hasBox K)
        (hasBox L)
        (hasBox M)

        (noBox A)
        (noBox B)
        (noBox C)
        (noBox D)
        (noBox E)
        (noBox F)
        (noBox G)
        (noBox H)
        (noBox I)
        (noBox N)
        (noBox O)
        (noBox P)
        (noBox Q)
        (noBox R)
        
        (robotHasEmptyHands)
        (onGround)
    )

    (:goal 	(and
    			(hasSwitchOn C)
                ;(hasSwitchOn N)
                ;(hasShakey G)
    		)
    )

)